csc/dcaf

modules/kvm-host/reset.yml, modules/kvm-host/roles/common-physical/tasks/main.yml, modules/kvm-host/roles/common-virtual/tasks/main.yml, modules/kvm-host/roles/dhcpd/tasks/main.yml, modules/kvm-host/roles/ovs/tasks/main.yml, modules/kvm-host/roles/ovs/templates/ifcfg-bond.j2, modules/kvm-host/roles/ovs/templates/ifcfg-em3.j2, modules/kvm-host/roles/ovs/templates/ifcfg-ovsbr.j2, modules/kvm-host/site.yml
This PR address issues found while testing with a large inventory.
```
TASK [vm-vlans : Set eth1 to default route] ************************************
changed: [controller-3]
changed: [controller-2]
changed: [haproxy-2]
changed: [network-3]
changed: [swift-2]
changed: [network-2]
changed: [swift-3]
changed: [controller-1]
changed: [haproxy-1]
changed: [network-1]
changed: [swift-1]
TASK [vm-vlans : Restart all interfaces] ***************************************
changed: [controller-3]
changed: [swift-3]
changed: [network-3]
changed: [network-2]
changed: [swift-2]
changed: [controller-2]
changed: [haproxy-2]
changed: [controller-1]
changed: [network-1]
changed: [haproxy-1]
changed: [swift-1]
PLAY RECAP *********************************************************************
auto-deploy-node …
```
=> fixes to kvm-host networking during testing

modules/kvm-host/roles/create-vm/tasks/main.yml, modules/kvm-host/roles/vm-initialization/tasks/main.yml
```
TASK [vm-vlans : Set eth1 to default route] ************************************
changed: [controller-2]
changed: [controller-3]
changed: [haproxy-2]
changed: [network-2]
changed: [network-3]
changed: [swift-2]
changed: [swift-3]
changed: [controller-1]
changed: [haproxy-1]
changed: [network-1]
changed: [swift-1]
TASK [vm-vlans : Restart all interfaces] ***************************************
changed: [controller-3]
changed: [network-3]
changed: [swift-2]
changed: [swift-3]
changed: [controller-2]
changed: [haproxy-2]
changed: [network-2]
changed: [controller-1]
changed: [haproxy-1]
changed: [network-1]
changed: [swift-1]
PLAY RECAP *********************************************************************
auto-deploy-node           : ok=10   changed=3    unreachable=0    failed=0
basevm …
```
=> remove static pauses, and replace with wait_for module

modules/kvm-host/roles/rhsm/tasks/main.yml
adding of the subscription-manager role. 
Completed run is shown in Pull 13
=> adding sub manager role

docsite/source/overview.rst
Changes to the overview.rst to include a brief description of the modules in DCAF.
=> docs - overview

modules/autodeploynode/roles/base/tasks/main.yml
Change location of the inventory in the ansible.cfg
=> ansible.cfg changes

docsite/source/quickstart.rst, docsite/source/quickstart_autodeploynode.rst
This is the initial PR for the quickstart guides. As each guide is submitted there is code cleanup that has to be done so they will be submitted as they are worked.
First is the quickstart guide, which is a reference to the others.
The first quickstart guide is the autodeploynode.
The next PR will be the autodeploynode cleanup.
=> quickstart guides

modules/kvm-host/README.md
Update to the kvm-host module readme
=> update to README.md

modules/kvm-host/reset.yml, modules/kvm-host/roles/dhcpd/tasks/main.yml, modules/kvm-host/roles/vm-vlans/tasks/main.yml, modules/kvm-host/roles/vm-vlans/templates/ifcfg-lvnet.j2, modules/kvm-host/site.yml
During testing all vms came up, but were not accessible on any nic except eth0. 
Found issues in that the nics and the virtual networks were not matched up properly.
This PR:
resolved issue where vm-vlans were assigning out of order, resolved i…ssue where dhcpd was being restarted too many times, to quickly and failing
```
TASK [vm-vlans : Add VLAN interfaces to VMs] ***********************************
changed: [network-3 -> None] => (item=nic1)
changed: [network-3 -> None] => (item=nic2)
changed: [network-3 -> None] => (item=nic3)
changed: [network-3 -> None] => (item=nic4)
changed: [network-3 -> None] => (item=nic5)
changed: [controller-3 -> None] => (item=eth1)
changed: [controller-3 -> None] => (item=eth2)
changed: [controller-3 -> None] => (item=eth3)
changed: [controller-3 -> None] …
```
=> vm-vlan ordering fix

docsite/source/quickstart_bare_metal_os.rst, docsite/source/quickstart_slimer.rst
This is the quickstart quide for bare-metal-os.
=> quickstart bare-metal-os

modules/autodeploynode/library/selenium.py
As per https://github.com/ansible/ansible-modules-core/issues/2629
Testing
```
TASK [Find the RHEL DVD ISO file url] ******************************************
ok: [localhost]
TASK [Download the RHEL DVD ISO file to /opt/autodeploy/resources/ISO] *********
ok: [localhost]
```
=> Bugfix for booleans in selenium module

docsite/source/index.rst, docsite/source/rhel_osp_module.rst
The doc for the rhel-osp module.
=> rhel-osp module doc

docsite/source/autodeploynode_module.rst, docsite/source/index.rst
This is the doc for the autodeploynode module, it replaces the previous config_autodeploy_node.
Removed the offline mode from the index.
=> autodeploynode module doc

docsite/source/bare_metal_os_module.rst, docsite/source/kvm_host_module.rst, docsite/source/overview.rst, docsite/source/rhel_osp_module.rst, modules/bare-metal-os/inventory/hosts.ini, modules/kvm-host/inventory/group_vars/kvm_host.yml, modules/kvm-host/inventory/hosts.ini, modules/rhel-osp/inventory/hosts.ini
KVM-Host module doc
Changes to other module docs and related files
=> kvm-host module doc and changes

docsite/source/autodeploynode_module.rst, docsite/source/quickstart_ansible_scaleio.rst
Minor documentation corrections
=> Correcting syntax errors

docsite/source/index.rst, docsite/source/quickstart.rst, docsite/source/quickstart_vmware.rst, docsite/source/vmware_module.rst
VMware module doc and quick start guide
=> vmware-module-doc

docsite/source/autodeploynode_module.rst, docsite/source/bare_metal_os_module.rst, docsite/source/kvm_host_module.rst, docsite/source/quickstart_ansible_scaleio.rst, docsite/source/quickstart_autodeploynode.rst, docsite/source/quickstart_bare_metal_os.rst, docsite/source/quickstart_kvm_host.rst, docsite/source/quickstart_rhel_osp.rst, docsite/source/quickstart_slimer.rst, docsite/source/rhel_osp_module.rst
These are some documentation updates.
=> document updates

modules/autodeploynode/library/hanlon_model.py, modules/bare-metal-os/library/hanlon_model.py, modules/vmware/library/hanlon_model.py
Added a check to make sure ANSIBLE_VERSION was defined.
Used newly added global function _load_params() to grab the parameters before execution of AnsibleModule.
@mtnbikenc performed the testing of the module.
=> Modifications to hanlon model module to support 2.1

modules/autodeploynode/build.sh
Tested autodeploynode and bare-metal-os modules in a VM.
```
[root@rhel72 ~]# ansible-playbook /opt/autodeploy/projects/dcaf/modules/autodeploynode/main.yml
[WARNING]: provided hosts list is empty, only localhost is available
PLAY [Configure autodeploynode base requirements] ******************************
TASK [setup] *******************************************************************
ok: [localhost]
TASK [base : Install required support packages] ********************************
changed: [localhost] => (item=[u'dhcp', u'docker', u'firefox', u'genisoimage', u'httpd', u'ipmitool', u'iptables-services', u'ntp', u'python-netaddr', u'python-passlib', u'python-pip', u'python-xvfbwrapper', u'sshpass', u'unzip', u'vim', u'wget', u'xorg-x11-server-Xvfb', u'yum-utils', u'openssl-devel', …
```
=> Updating to Ansible 2.1

modules/autodeploynode/initial_stage.yml, modules/autodeploynode/roles/base/defaults/main.yml, modules/autodeploynode/roles/base/tasks/main.yml, modules/autodeploynode/roles/base/vars/main.yml, modules/autodeploynode/roles/dhcp-server/defaults/main.yml, modules/autodeploynode/roles/dhcp-server/tasks/main.yml, modules/autodeploynode/roles/dhcp-server/vars/main.yml, modules/autodeploynode/roles/hanlon-discover/tasks/main.yml, modules/autodeploynode/roles/hanlon-discover/vars/main.yml, modules/autodeploynode/roles/hanlon-docker/tasks/main.yml, modules/autodeploynode/roles/hanlon-docker/vars/main.yml
Added a few comments for clarity as reading through documentation.
=> added comments to module

modules/bare-metal-os/minimize-rhel-iso.yml
I wrote this a while back to replace the minimize script to pure Ansible.
It needs to be tested before integrated into the prepare role.
=> Adding RHEL minimize playbook
